server:
  forward-headers-strategy: framework

spring:
  cloud:
    # discovery.enabled=true 时 SCA 会联动 spring.cloud.discovery.enabled
    nacos:
      discovery:
        enabled: true
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP
      config:
        enabled: true
        namespace: ${spring.profiles.active}
        group: DEFAULT_GROUP
        file-extension: yaml
